import GlobalSpinner from '@components/GlobalSpinner';
import GlobalAlert from './components/alert/GlobalAlert';
import Providers from './provider';
import RouteChangeHandler from '@components/RouteChangeHandler';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
        <GlobalAlert />
        <GlobalSpinner />
        <RouteChangeHandler />
      </body>
    </html>
  );
}
