import GlobalAlert from "./components/alert/globalAlert"
import Providers from "./provider"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
        <GlobalAlert />
      </body>
    </html>
  )
}
